import { Activity, CheckCircle2, Database, ExternalLink, Gauge, RefreshCw, Server, TriangleAlert, UsersRound } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import type { Provider } from '@workspace/api-client-react';
import { getGetDashboardSummaryQueryKey, getListJobsQueryKey, getListProvidersQueryKey, useGetDashboardSummary, useListJobs, useListProviders } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';

function Stat({ label, value, note, accent = false }: { label: string; value: string | number; note: string; accent?: boolean }) {
  return <div className={`rounded-2xl border p-5 ${accent ? 'border-[#c5df57]/30 bg-[#c5df57]/10' : 'border-white/10 bg-white/[.045]'}`}><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-white/45">{label}</p><p className={`mt-5 font-display text-4xl font-semibold tracking-[-.07em] ${accent ? 'text-[#c5df57]' : 'text-white'}`} data-testid={`text-admin-${label.toLowerCase().replaceAll(' ', '-')}`}>{value}</p><p className="mt-2 text-xs text-white/40">{note}</p></div>;
}

function ProviderRow({ provider }: { provider: Provider }) {
  return <div className="flex items-center justify-between gap-4 border-b border-white/10 py-4 last:border-0" data-testid={`row-provider-${provider.id}`}><div className="flex min-w-0 items-center gap-3"><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: provider.accent || '#c5df57' }} /><div className="min-w-0"><p className="truncate text-sm font-semibold text-white">{provider.label}</p><p className="truncate text-xs text-white/40">{provider.domains.join(' · ')}</p></div></div><span className={`shrink-0 rounded-full px-2 py-1 text-[9px] font-bold uppercase tracking-[.12em] ${provider.enabled ? 'bg-[#c5df57]/15 text-[#c5df57]' : 'bg-white/10 text-white/40'}`}>{provider.enabled ? 'Enabled' : 'Paused'}</span></div>;
}

export default function AdminPage() {
  const queryClient = useQueryClient();
  const summary = useGetDashboardSummary({ query: { queryKey: getGetDashboardSummaryQueryKey(), refetchInterval: 10000 } });
  const providers = useListProviders({ query: { queryKey: getListProvidersQueryKey(), refetchInterval: 15000 } });
  const jobs = useListJobs({ query: { queryKey: getListJobsQueryKey(), refetchInterval: 5000 } });
  const refresh = () => { queryClient.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); queryClient.invalidateQueries({ queryKey: getListProvidersQueryKey() }); queryClient.invalidateQueries({ queryKey: getListJobsQueryKey() }); };
  const data = summary.data;
  const providerData = providers.data || [];
  const jobData = jobs.data || [];

  return (
    <AppShell admin>
      <main className="mx-auto max-w-[1240px] px-5 py-10 sm:px-8 sm:py-16">
        <div className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono-ui text-[10px] font-semibold uppercase tracking-[.18em] text-[#c5df57]">Internal / operations</p><h1 className="mt-3 font-display text-5xl font-semibold tracking-[-.07em] sm:text-7xl">Keep an eye<br /><span className="text-white/35">on the quiet.</span></h1></div><button onClick={refresh} className="flex w-fit items-center gap-2 rounded-full border border-white/15 px-4 py-2.5 text-xs font-semibold text-white/70 hover:border-white/30 hover:text-white" data-testid="button-refresh-admin"><RefreshCw className="h-3.5 w-3.5" /> Refresh data</button></div>
        <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" data-testid="section-admin-summary">
          {summary.isLoading ? [1, 2, 3, 4].map((item) => <div key={item} className="h-[150px] animate-pulse rounded-2xl bg-white/[.06]" data-testid="status-admin-summary-loading" />) : data ? <><Stat label="Total jobs" value={data.totalJobs} note="Since service start" /><Stat label="Completed" value={data.completedJobs} note={`${data.totalJobs ? Math.round((data.completedJobs / data.totalJobs) * 100) : 0}% completion rate`} accent /><Stat label="In process" value={data.processingJobs} note="Live right now" /><Stat label="Saved bytes" value={data.savedBytes} note={`Retained for ${data.retentionHours} hours`} /></> : <div className="col-span-full rounded-2xl border border-[#f1a38b]/30 bg-[#f1a38b]/10 p-5 text-sm text-[#f1c3b3]" data-testid="status-admin-summary-error"><TriangleAlert className="mb-2 h-5 w-5" />Summary is temporarily unavailable. <button onClick={refresh} className="font-bold underline underline-offset-4">Retry</button></div>}
        </section>
        <div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_.9fr]">
          <section className="rounded-2xl border border-white/10 bg-white/[.045] p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-white/40">Live queue</p><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-.05em]">Recent activity</h2></div><Activity className="h-5 w-5 text-[#c5df57]" /></div>{jobs.isLoading && <div className="space-y-3">{[1, 2, 3, 4].map((item) => <div key={item} className="h-14 animate-pulse rounded-xl bg-white/[.06]" />)}</div>}{jobs.isError && <div className="rounded-xl bg-[#f1a38b]/10 p-4 text-xs text-[#f1c3b3]" data-testid="status-admin-jobs-error">Could not load the queue. <button onClick={() => jobs.refetch()} className="font-bold underline">Retry</button></div>}{!jobs.isLoading && !jobs.isError && jobData.length === 0 && <div className="py-10 text-center text-sm text-white/40" data-testid="status-admin-jobs-empty">No jobs have been created yet.</div>}<div>{jobData.slice(0, 7).map((job) => <div key={job.id} className="flex items-center justify-between gap-3 border-b border-white/10 py-3 last:border-0" data-testid={`row-admin-job-${job.id}`}><div className="min-w-0"><p className="truncate text-sm font-semibold text-white/85">{job.title || 'Untitled media'}</p><p className="mt-1 truncate text-[11px] text-white/35">{job.provider} · {job.format} · {job.status}</p></div><span className="font-mono-ui text-[10px] text-white/35">{job.progress}%</span></div>)}</div></section>
          <section className="rounded-2xl border border-white/10 bg-white/[.045] p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.16em] text-white/40">Provider health</p><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-.05em]">Source matrix</h2></div><Server className="h-5 w-5 text-[#f1a38b]" /></div>{providers.isLoading && <div className="space-y-3">{[1, 2, 3].map((item) => <div key={item} className="h-14 animate-pulse rounded-xl bg-white/[.06]" />)}</div>}{providers.isError && <div className="rounded-xl bg-[#f1a38b]/10 p-4 text-xs text-[#f1c3b3]" data-testid="status-admin-providers-error">Provider data is unavailable. <button onClick={() => providers.refetch()} className="font-bold underline">Retry</button></div>}{!providers.isLoading && !providers.isError && providerData.length === 0 && <div className="py-10 text-center text-sm text-white/40" data-testid="status-admin-providers-empty">No providers configured.</div>}<div>{providerData.map((provider) => <ProviderRow key={provider.id} provider={provider} />)}</div><div className="mt-6 grid grid-cols-3 gap-2 border-t border-white/10 pt-5 text-center"><div><Gauge className="mx-auto h-4 w-4 text-[#c5df57]" /><p className="mt-2 text-[10px] uppercase tracking-[.1em] text-white/35">Latency</p><p className="mt-1 font-mono-ui text-xs text-white/70">nominal</p></div><div><Database className="mx-auto h-4 w-4 text-[#f1a38b]" /><p className="mt-2 text-[10px] uppercase tracking-[.1em] text-white/35">Storage</p><p className="mt-1 font-mono-ui text-xs text-white/70">ephemeral</p></div><div><CheckCircle2 className="mx-auto h-4 w-4 text-[#c5df57]" /><p className="mt-2 text-[10px] uppercase tracking-[.1em] text-white/35">Status</p><p className="mt-1 font-mono-ui text-xs text-white/70">healthy</p></div></div></section>
        </div>
        <div className="mt-8 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-[#c5df57]/10 px-5 py-4 text-xs text-white/55"><span className="flex items-center gap-2"><UsersRound className="h-4 w-4 text-[#c5df57]" /> Consumer surfaces are intentionally separate from this view.</span><span className="flex items-center gap-1 font-mono-ui text-[10px] uppercase tracking-[.1em]">Read-only snapshot <ExternalLink className="h-3 w-3" /></span></div>
      </main>
    </AppShell>
  );
}